---

- name: Create Kubernetes config directory
  file:
    path: "{{ kube_manifest_dir }}"
    state: directory

- name: Copy Kubernetes apiserver yml config file
  template:
    src: "kube-apiserver.yml.j2"
    dest: "{{ kube_manifest_dir }}/kube-apiserver.yml"

- name: Copy Kubernetes controller-manager yml config file
  template:
    src: "kube-controller-manager.yml.j2"
    dest: "{{ kube_manifest_dir }}/kube-controller-manager.yml"

- name: Copy Kubernetes scheduler yml config file
  template:
    src: "kube-scheduler.yml.j2"
    dest: "{{ kube_manifest_dir }}/kube-scheduler.yml"

- name: Copy Kubernetes admin account config file
  template:
    src: "admin.conf.j2"
    dest: "{{ kubeadmin_config }}"

- name: Copy SSL certificate from ansible host
  copy:
    src: "{{ cert_dir }}"
    dest: "{{ kube_etc_dir }}"

- name: Create Kubernetes component symlinks
  file:
    src: "{{ downloads.kube.dir }}/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
    force: yes
  with_items:
    - kubectl
    - kubelet

- name: Create Kubernetes Helm symlinks
  file:
    src: "{{ downloads.helm.dir }}/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
    force: yes
  with_items: [ helm ]
